//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.25 at 04:35:40 PM IST 
//


package com.sqlToJson.BindingPojo;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sqlToJson.BindingPojo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sqlToJson.BindingPojo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Dlineage }
     * 
     */
    public Dlineage createDlineage() {
        return new Dlineage();
    }

    /**
     * Create an instance of {@link Dlineage.Relation }
     * 
     */
    public Dlineage.Relation createDlineageRelation() {
        return new Dlineage.Relation();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Dlineage.Table }
     * 
     */
    public Dlineage.Table createDlineageTable() {
        return new Dlineage.Table();
    }
      public Dlineage.View createDlineageView() {
        return new Dlineage.View();
    }
    /**
     * Create an instance of {@link Dlineage.Resultset }
     * 
     */
    public Dlineage.Resultset createDlineageResultset() {
        return new Dlineage.Resultset();
    }

    /**
     * Create an instance of {@link Dlineage.Relation.Target }
     * 
     */
    public Dlineage.Relation.Target createDlineageRelationTarget() {
        return new Dlineage.Relation.Target();
    }

    /**
     * Create an instance of {@link Dlineage.Relation.Source }
     * 
     */
    public Dlineage.Relation.Source createDlineageRelationSource() {
        return new Dlineage.Relation.Source();
    }

}
